### ISSUE TITLE
TypeError: Cannot read property 'exclude' of undefined

### ISSUE THREAD

**Issue by jnreynoso** [tkvw/react-app-rewire-graphql-tag#2]
Hi, 
I found the following error

```shell
/home/user/Coders/riqra/riqra-admin/node_modules/react-app-rewire-graphql-tag/index.js:6
    fileLoader.exclude.push(gqlExtension);
               ^
TypeError: Cannot read property 'exclude' of undefined
    at rewireGraphQLTag (/home/user/Coders/riqra/riqra-admin/node_modules/react-app-rewire-graphql-tag/index.js:6:16)
    at Object.override [as webpack] (/home/user/Coders/riqra/riqra-admin/config-overrides.js:8:12)
    at Object.<anonymous> (/home/user/Coders/riqra/riqra-admin/node_modules/react-app-rewired/scripts/start.js:13:13)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
error Command failed with exit code 1.
```
this is my configuration: 
```javascript
const { injectBabelPlugin } = require('react-app-rewired')
const rewireLess = require('react-app-rewire-less-modules')
const rewireGqlTag = require('react-app-rewire-graphql-tag')

module.exports = function override (config, env) {
  config = injectBabelPlugin(['import', { libraryName: 'antd', style: true }], config)

  config = rewireGqlTag(config, env)

  config = rewireLess.withLoaderOptions(
    `${env === 'production' ? 'foobar' : '[local]'}-[hash:base64:8]`
  )(config, env)

  return config
}
```

**Comment by draco** [comment]
I think the author is using `file-loader` in his config whereas in ours, we don't.

Adding a check to see if `file-loader` exists first before applying the exclusion seems to solve the problem for me.

```js
function rewireGraphQLTag(config, env) {
  const gqlExtension = /\.(graphql|gql)$/

  const fileLoader = config.module.rules.find(
    rule => rule.loader && rule.loader.indexOf('file-loader') !== -1
  )

  if (fileLoader !== undefined) {
    fileLoader.exclude.push(gqlExtension)
  }

  const gqlTagRule = {
    test: gqlExtension,
    loader: 'graphql-tag/loader',
    exclude: /node_modules/,
  }
  config.module.rules.push(gqlTagRule)

  return config
}
```

I have also opened a PR #3.

**Comment by jnreynoso** [comment]
HI @draco, followed his recommendations, but I got this error:
```javacript
Error: Expecting a parsed GraphQL document. Perhaps you need to wrap the query string in a "gql" tag? http://docs.apollostack.com/apollo-client/core.html#gql
```

```javascript
const { injectBabelPlugin } = require('react-app-rewired')
const rewireLess = require('react-app-rewire-less-modules')

function rewireGraphQLTag (config, env) {
  const gqlExtension = /\.(graphql|gql)$/

  const fileLoader = config.module.rules.find(
    rule => rule.loader && rule.loader.indexOf('file-loader') !== -1
  )

  if (fileLoader !== undefined) {
    fileLoader.exclude.push(gqlExtension)
  }

  const gqlTagRule = {
    test: gqlExtension,
    loader: 'graphql-tag/loader',
    exclude: /node_modules/
  }
  config.module.rules.push(gqlTagRule)

  return config
}

module.exports = function override (config, env) {
  config = injectBabelPlugin(['import', { libraryName: 'antd', style: true }], config)

  config = rewireLess.withLoaderOptions(
    `${env === 'production' ? 'foobar' : '[local]'}-[hash:base64:8]`
  )(config, env)

  config = rewireGraphQLTag(config, env)

  return config
}
```

**Comment by draco** [comment]
hey @jnreynoso I am no longer using this plugin at the moment but when I did, the imported file was the actual query.

```gql
// query.gql

query something {
  // ... the query
}
```

How are you exporting and importing your `gql` files, and how do the content of your `gql` file look like? The way I imported and exported might be a bit different as I was using TypeScript.

**Comment by loganpowell** [comment]
Having this same issue:

```
yarn start v0.22.0
$ react-app-rewired start
C:\Users\surface\Projects\Bootcamp\census\graphql\RAATS\node_modules\react-app-rewire-graphql-tag\index.js:6
    fileLoader.exclude.push(gqlExtension);
               ^

TypeError: Cannot read property 'exclude' of undefined
    at rewireGraphQLTag (C:\Users\surface\Projects\Bootcamp\census\graphql\RAATS\node_modules\react-app-rewire-graphql-tag\index.js:6:16)
    at Object.override [as webpack] (C:\Users\surface\Projects\Bootcamp\census\graphql\RAATS\config-overrides.js:7:12)
    at Object.<anonymous> (C:\Users\surface\Projects\Bootcamp\census\graphql\RAATS\node_modules\react-app-rewired\scripts\start.js:13:13)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
error Command failed with exit code 1.
```

Any progress?

**Comment by tkvw** [comment]
This should be fixed in 1.1.0, sorry for the late response.

**Comment by loganpowell** [comment]
Do you mean the commit you just made? I just downloaded this this morning...

**Comment by tkvw** [comment]
yes, the commit I just made (it's updated on npm as well)

**Comment by loganpowell** [comment]
Just a quick question, this:

https://github.com/detrohutt/react-app-rewire-inline-import-graphql-ast

seems to be pretty popular. Is this a drop-in for your library?

**Comment by loganpowell** [comment]
It looks like a port from:

https://www.npmjs.com/package/babel-plugin-inline-import-graphql-ast
